config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :weather_lookups, only: [:index, :create, :show]
  root to: "weather_lookups#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/weather_lookup.rb
class WeatherLookup < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_lookups_controller.rb
class WeatherLookupsController < ApplicationController

  def index
    if(!flash[:alert] && params[:weather_lookup])
      @weather_lookup = WeatherLookup.find(params[:weather_lookup])
    end
    
    @weather_lookups  = WeatherLookup.all.order("created_at DESC").paginate(page: params[:page], per_page: 10)
  end
  
  def show
    @weather_lookup = WeatherLookup.find(params[:id])
  end
  
  def create
    #Get the unit type from the form. Default to "imperial" if none passed
    if(params[:units] == "imperial")
      units = params[:units]
      unit_label_temp = "&deg;F"
      unit_label_sind_speed = "mph"
    elsif(params[:units] == "celsius")
      units = params[:units]
      unit_label_temp = "&deg;C"
      unit_label_sind_speed = "m/s"
    else
      units = "imperial"
      unit_label_temp = "&deg;F"
      unit_label_sind_speed = "mph"
    end
    
    #Set and modify city & state variables from params (could validate and cleanup input here)
    city = params[:city].capitalize
    country = params[:country].upcase
    
    #Setup API URL params
    url = URI("http://api.openweathermap.org/data/2.5/weather?APPID=548f74cb6175f246fce62d7bca56a380&q=#{city},#{country}&units=#{units}")
  
    #Call API
    http = Net::HTTP.new(url.host, url.port)
    request = Net::HTTP::Get.new(url)
    request["Cache-Control"] = 'no-cache'
    
    #Format API response
    response = http.request(request)
    weather_data = JSON.parse(response.body, object_class: JSON::GenericObject)

    #Display error code, or temperature based on API response
    if(weather_data.cod == "404") #API call failed
      flash[:alert] = "Error: #{weather_data.message}<br>"
      flash[:alert] += "City: #{city}<br>Country: #{country}<br>"
    else #API call success
      
      weather_data['weather'].each do |weather|
        @weather_desc = "#{weather['description'].titlecase}"
      end
      
      #Write session variables for map
      @popover = ""
      @popover += "<b>Weather:</b> <span class='current-weather'>#{@weather_desc}</span><br>"
      @popover += "<b>Temperature:</b> <span class='current-temp'>#{weather_data.main.temp}#{unit_label_temp}</span><br>"
      @popover += "<b>Humidity:</b> <span class='current-humidity'>#{weather_data.main.humidity}%</span>"
      
      @weather_lookup = WeatherLookup.create(
                        :city => weather_data.name,
                        :country => weather_data.sys.country,
                        :weather => @weather_desc,
                        :temp => "#{weather_data.main.temp}#{unit_label_temp}",
                        :pressure => "#{weather_data.main.pressure} h",
                        :humidity => "#{weather_data.main.humidity}%",
                        :wind_speed => "#{weather_data.wind.speed} #{unit_label_sind_speed}",
                        :wind_dir => "#{weather_data.wind.deg}&deg;",
                        :sunrise => Time.at(weather_data.sys.sunrise).utc,
                        :sunset => Time.at(weather_data.sys.sunset).utc,
                        :lat => weather_data.coord.lat.to_f,
                        :lon => weather_data.coord.lon.to_f,
                        :popover => @popover
                      )
    end

    redirect_to root_path(:weather_lookup => @weather_lookup)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather_lookups/index.html.erb
<div id="carouselIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselIndicators" data-slide-to="1"></li>
    <li data-target="#carouselIndicators" data-slide-to="2"></li>
    <li data-target="#carouselIndicators" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "carousel/sunny.jpg", class: "d-block w-100", alt: "Sunny" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel/muddy.jpg", class: "d-block w-100", alt: "Sunny" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel/snowy.jpg", class: "d-block w-100", alt: "Sunny" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel/rainy.jpg", class: "d-block w-100", alt: "Sunny" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container">
  <div class="row main-row">
    <div class="col">
      <h1>Weather Lookup App</h1>
      <p>Use the form below to get the current weather in any city!</p>
      
      <%- if flash[:notice] -%>
        <div class="alert alert-info" role="alert">
          <%= flash[:notice].html_safe %>
        </div>
      <%- end -%>
      <%- if flash[:alert] -%>
        <div class="alert alert-danger" role="alert">
          <%= flash[:alert].html_safe %>
        </div>
      <%- end -%>
      
      <%= form_tag(weather_lookups_path, multipart: true, role: 'form') do %>
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= label_tag 'city', 'City' %>
            <%= text_field_tag 'city', nil, placeholder: 'What city do you want to lookup?', class: 'form-control' %>
          </div><!-- /.form-group -->
          <div class="form-group col-md-6">
            <%= label_tag 'country', 'Country' %>
            <%= text_field_tag 'country', nil, placeholder: 'What country is your city in?', class: 'form-control' %>
          </div><!-- /.form-group -->
        </div><!-- /.form-row -->
  
        <div class="form-row">
          <div class="col">
            <div class="form-check form-check-inline">
              <%= radio_button_tag 'units', 'imperial', true, class: 'form-check-input' %>
              <%= label_tag 'units_imperial', 'Fahrenheit', class: 'form-check-label' %>
            </div>
            <div class="form-check form-check-inline">
              <%= radio_button_tag 'units', 'celsius', false, class: 'form-check-input' %>
              <%= label_tag 'units_celsius', 'Celsius', class: 'form-check-label' %>
            </div>
          </div><!-- /.col -->
        </div><!-- /.form-row -->
  
        <%= button_tag 'Get the current weather', class: 'btn btn-primary form-btn' %>
      <% end %>
    </div><!-- /.col -->
  </div><!-- /.row -->
  
  <%- if @weather_lookup -%>
    <div class="row main-row">
      <div class="col">
        <div class="card">
          <div class="card-header">
            <%= @weather_lookup.city %>, <%= @weather_lookup.country %> Weather on <%= local_time(@weather_lookup.created_at) %>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="row">
              <div class="col">
                <p>
                  <b>Weather:</b> <span class='current-weather'><%= @weather_lookup.weather %></span><br>
                  <b>Temperature:</b> <span class='current-temp'><%= @weather_lookup.temp.html_safe %></span><br>
                  <b>Pressure:</b> <span class='current-pressure'><%= @weather_lookup.pressure %></span><br>
                  <b>Humidity:</b> <span class='current-humidity'><%= @weather_lookup.humidity %></span><br>
                </p>
              </div><!-- /.col -->
              <div class="col">
                <p>
                  <b>Wind Speed:</b> <span class='current-wind-speed'><%= @weather_lookup.wind_speed %></span><br>
                  <b>Wind Direction:</b> <span class='current-wind-direction'><%= @weather_lookup.wind_dir.html_safe %></span><br>
                  <b>Sunrise:</b> <span class='sunrise'><%= local_time(@weather_lookup.sunrise, '%l:%M%P') %></span><br>
                  <b>Sunset:</b> <span class='sunset'><%= local_time(@weather_lookup.sunset, '%l:%M%P') %></span><br>
                </p>
              </div><!-- /.col -->
            </div><!-- /.row -->
          </div><!-- /.card-body -->
        </div><!-- /.card -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  
    <%- if @weather_lookup.lat && @weather_lookup.lon -%>
      <div class="row main-row">
        <div class="col">
          <%= 
            map(
              :center => {
                :latlng => [@weather_lookup.lat, @weather_lookup.lon],
                :zoom => 12
              },
              :markers => [{
                :latlng => [@weather_lookup.lat, @weather_lookup.lon],
                :popup => session[:popover]
              }],
              :minZoom => 9
            )
          %>
        </div><!-- /.col -->
      </div><!-- /.row -->
    <%- end -%>
  <%- end -%>

  <div class="row main-row">
    <div class="col">
      <h2>Historic Lookups</h2>
      <table class="table table-striped table-bordered weather_lookups">
        <thead>
          <tr>
            <th>City</th>
            <th>Country</th>
            <th>Temperature</th>
            <th>Timestamp</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <%- @weather_lookups.each do |weather_lookup| -%>
            <tr>
              <td><%= weather_lookup.city %></td>
              <td><%= weather_lookup.country %></td>
              <td><%= weather_lookup.temp.html_safe %></td>
              <td><%= local_time(weather_lookup.created_at) %></td>
              <td><%= link_to('View Details', weather_lookup, class: 'btn btn-info btn-sm') %></td>
            </tr>
          <%- end -%>
        </tbody>
      </table>
      <%= will_paginate @weather_lookups %>
    </div><!-- /.col -->
  </div><!-- /.row -->
  
</div><!-- /.container -->

app/views/weather_lookups/show.html.erb
<%- if @weather_lookup.lat && @weather_lookup.lon -%>
  <div class="row no-gutters main-row">
    <div class="col">
      <%= 
        map(
          :center => {
            :latlng => [@weather_lookup.lat, @weather_lookup.lon],
            :zoom => 12
          },
          :markers => [{
            :latlng => [@weather_lookup.lat, @weather_lookup.lon],
            :popup => session[:popover]
          }],
          :minZoom => 9
        )
      %>
    </div><!-- /.col -->
  </div><!-- /.row -->
<%- end -%>
<div class="container">
  <div class="row main-row">
    <div class="col">
      <h1>Historic Lookup #<%= @weather_lookup.id %> <%= link_to("Back", root_path, class: "btn btn-primary btn-sm") %></h1>
      <div class="card">
        <div class="card-header">
          <%= @weather_lookup.city %>, <%= @weather_lookup.country %> Weather on <%= local_time(@weather_lookup.created_at) %>
        </div><!-- /.card-header -->
        <div class="card-body">
          <div class="row">
            <div class="col">
              <p>
                <b>Weather:</b> <span class='current-weather'><%= @weather_lookup.weather %></span><br>
                <b>Temperature:</b> <span class='current-temp'><%= @weather_lookup.temp.html_safe %></span><br>
                <b>Pressure:</b> <span class='current-pressure'><%= @weather_lookup.pressure %></span><br>
                <b>Humidity:</b> <span class='current-humidity'><%= @weather_lookup.humidity %></span><br>
              </p>
            </div><!-- /.col -->
            <div class="col">
              <p>
                <b>Wind Speed:</b> <span class='current-wind-speed'><%= @weather_lookup.wind_speed %></span><br>
                <b>Wind Direction:</b> <span class='current-wind-direction'><%= @weather_lookup.wind_dir.html_safe %></span><br>
                <b>Sunrise:</b> <span class='sunrise'><%= local_time(@weather_lookup.sunrise, '%l:%M%P') %></span><br>
                <b>Sunset:</b> <span class='sunset'><%= local_time(@weather_lookup.sunset, '%l:%M%P') %></span><br>
              </p>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.card-body -->
      </div><!-- /.card -->
    </div><!-- /.col -->
  </div><!-- /.row -->
</div><!-- /.container -->